<?php

namespace ContainerXFn69fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Luv6nW_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.luv6nW.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.luv6nW.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.luv6nW..App\\Entity\\Orders', NULL, 'Cannot autowire service ".service_locator.luv6nW.": it references class "App\\Entity\\Orders" but no such service exists.'],
        ], [
            'order' => 'App\\Entity\\Orders',
        ]);
    }
}
