<?php

namespace ContainerXFn69fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OAfuJNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OAfuJ_n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OAfuJ_n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartService' => ['privates', 'App\\Service\\Cart\\CartService', 'getCartServiceService', true],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'cartService' => 'App\\Service\\Cart\\CartService',
            'session' => '?',
        ]);
    }
}
