<?php

namespace ContainerXFn69fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QJr8q9hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qJr8q9h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qJr8q9h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminArticlesController::delete' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\Admin\\AdminArticlesController::edit' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.TDHlZNm', 'get_ServiceLocator_TDHlZNmService', true],
            'App\\Controller\\ArticlesController::show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.V9fBZw7', 'get_ServiceLocator_V9fBZw7Service', true],
            'App\\Controller\\CartController::less' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\CartController::saveOrder' => ['privates', '.service_locator.OAfuJ_n', 'get_ServiceLocator_OAfuJNService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\OrdersController::add' => ['privates', '.service_locator.FoM_s.4', 'get_ServiceLocator_FoMS_4Service', true],
            'App\\Controller\\OrdersController::index' => ['privates', '.service_locator.FoM_s.4', 'get_ServiceLocator_FoMS_4Service', true],
            'App\\Controller\\OrdersController::show' => ['privates', '.service_locator.luv6nW.', 'get_ServiceLocator_Luv6nW_Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::editMdp' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\AdminArticlesController:delete' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\Admin\\AdminArticlesController:edit' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.TDHlZNm', 'get_ServiceLocator_TDHlZNmService', true],
            'App\\Controller\\ArticlesController:show' => ['privates', '.service_locator.ewTmbP1', 'get_ServiceLocator_EwTmbP1Service', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.V9fBZw7', 'get_ServiceLocator_V9fBZw7Service', true],
            'App\\Controller\\CartController:less' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\CartController:saveOrder' => ['privates', '.service_locator.OAfuJ_n', 'get_ServiceLocator_OAfuJNService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\OrdersController:add' => ['privates', '.service_locator.FoM_s.4', 'get_ServiceLocator_FoMS_4Service', true],
            'App\\Controller\\OrdersController:index' => ['privates', '.service_locator.FoM_s.4', 'get_ServiceLocator_FoMS_4Service', true],
            'App\\Controller\\OrdersController:show' => ['privates', '.service_locator.luv6nW.', 'get_ServiceLocator_Luv6nW_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:editMdp' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\AdminArticlesController::delete' => '?',
            'App\\Controller\\Admin\\AdminArticlesController::edit' => '?',
            'App\\Controller\\ArticlesController::index' => '?',
            'App\\Controller\\ArticlesController::show' => '?',
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::less' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\CartController::saveOrder' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\OrdersController::add' => '?',
            'App\\Controller\\OrdersController::index' => '?',
            'App\\Controller\\OrdersController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::editMdp' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminArticlesController:delete' => '?',
            'App\\Controller\\Admin\\AdminArticlesController:edit' => '?',
            'App\\Controller\\ArticlesController:index' => '?',
            'App\\Controller\\ArticlesController:show' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:less' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\CartController:saveOrder' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\OrdersController:add' => '?',
            'App\\Controller\\OrdersController:index' => '?',
            'App\\Controller\\OrdersController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:editMdp' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
