<?php

namespace ContainerXFn69fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.luv6nW..App\Entity\Orders' shared service.
     *
     * @return \App\Entity\Orders
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.luv6nW.": it references class "App\\Entity\\Orders" but no such service exists.');
    }
}
