<?php

namespace ContainerXFn69fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SearchForm' shared autowired service.
     *
     * @return \App\Form\SearchForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SearchForm.php';

        return $container->privates['App\\Form\\SearchForm'] = new \App\Form\SearchForm();
    }
}
