<?php

namespace ContainerXFn69fw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebServer_Command_ServerLogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'web_server.command.server_log' shared service.
     *
     * @return \Symfony\Bundle\WebServerBundle\Command\ServerLogCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/web-server-bundle/Command/ServerLogCommand.php';

        $container->privates['web_server.command.server_log'] = $instance = new \Symfony\Bundle\WebServerBundle\Command\ServerLogCommand();

        $instance->setName('server:log');

        return $instance;
    }
}
