security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        from_database: 
            entity: 
                class: App\Entity\User
                property: email

<<<<<<< Updated upstream
<<<<<<< Updated upstream
                #username : admin
                #mdp : adminadmin
=======
        #username : admin
        #mdp : adminadmin
>>>>>>> Stashed changes
=======
        #username : admin
        #mdp : adminadmin
>>>>>>> Stashed changes

    #définir les composants pour définir les utilisateurs   
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout: 
                path: /logout
                target: /
            #lazy: true
            #provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            #http_basic: true
            form_login: 
                check_path: login

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        - { path: ^/home, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
=======
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/home, roles: ROLE_USER }
>>>>>>> Stashed changes
=======
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/home, roles: ROLE_USER }
>>>>>>> Stashed changes

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
<<<<<<< Updated upstream
<<<<<<< Updated upstream
            #Symfony\Component\Security\Core\User\User: plaintext : mot de passse afficher en clair
=======
            #Symfony\Component\Security\Core\User\User: plaintext : mot de passse afficher en claur
>>>>>>> Stashed changes
=======
            #Symfony\Component\Security\Core\User\User: plaintext : mot de passse afficher en claur
>>>>>>> Stashed changes
