<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXFn69fw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXFn69fw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXFn69fw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXFn69fw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXFn69fw\App_KernelDevDebugContainer([
    'container.build_hash' => 'XFn69fw',
    'container.build_id' => 'd126e94f',
    'container.build_time' => 1621191917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXFn69fw');
